application: horton-mcnelly-pickup-sports
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /static
  static_dir: static
  
#endpoints handler
- url: /_ah/spi/.*
  script: pickup_sports_api.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: pycrypto
  version: "2.6"
- name: endpoints
  version: latest